const Transaction = require("../models/TransactionModel");
const User = require("../models/UserModel");
const PDFDocument = require("pdfkit");

exports.generatePDF = async (req, res) => {
  try {
    const userId = req.user;
    // Extract filters from query parameters
    const { category, start, end, txId } = req.query;

    // 1. Fetch Filtered Data
    const user = await User.findById(userId);

    // Use the Universal Filter we built in the Model
    const transactions = await Transaction.findForReport(userId, {
      category,
      startDate: start,
      endDate: end,
      transactionId: txId,
    });

    if (!user) return res.status(404).json({ error: "User not found" });
    if (!transactions || transactions.length === 0) {
      return res
        .status(404)
        .json({ error: "No transactions found for this selection" });
    }

    // 2. Initialize PDF
    const doc = new PDFDocument({ margin: 50, bufferPages: true });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=KES_Tracker_Report.pdf`,
    );
    doc.pipe(res);

    // 3. HEADER & BRANDING
    doc
      .fontSize(22)
      .fillColor("#2E7D32")
      .text("KES TRACKER", { align: "right" });
    doc
      .fontSize(10)
      .fillColor("#000")
      .text("Professional Financial Statement", { align: "right" });
    doc.moveDown();

    // 4. USER DETAILS
    doc
      .fontSize(12)
      .font("Helvetica-Bold")
      .text(`Account Holder: ${user.full_name}`);
    doc
      .font("Helvetica")
      .fontSize(10)
      .text(`Phone Number: ${user.phone_number}`);
    doc.text(`Report Period: ${start || "Beginning"} - ${end || "Present"}`);
    doc.text(`Generated: ${new Date().toLocaleString("en-GB")}`);
    doc.moveDown();

    // 5. SUMMARY BOX
    // Calculate summary based ONLY on filtered transactions
    const totalIncome = transactions
      .filter((t) => t.type === "income")
      .reduce((sum, t) => sum + parseFloat(t.amount), 0);
    const totalExpense = transactions
      .filter((t) => t.type === "expense")
      .reduce((sum, t) => sum + parseFloat(t.amount), 0);
    const balance = totalIncome - totalExpense;

    const boxTop = doc.y;
    doc.rect(50, boxTop, 500, 70).fillAndStroke("#f9f9f9", "#2E7D32");
    doc
      .fillColor("#2E7D32")
      .fontSize(12)
      .text("Report Summary", 70, boxTop + 10);
    doc.fillColor("#000").fontSize(10);
    doc.text(`Income: KES ${totalIncome.toLocaleString()}`, 70, boxTop + 30);
    doc.text(`Expense: KES ${totalExpense.toLocaleString()}`, 200, boxTop + 30);

    const balanceColor = balance >= 0 ? "#1B5E20" : "#C62828";
    doc
      .fillColor(balanceColor)
      .font("Helvetica-Bold")
      .text(`Net Cash Flow: KES ${balance.toLocaleString()}`, 70, boxTop + 50);
    doc.font("Helvetica").fillColor("#000").moveDown(4);

    // 6. TRANSACTION TABLE HEADER
    doc.fontSize(12).text("Transaction History", { underline: true });
    doc.moveDown(0.5);

    const tableTop = doc.y;
    doc.fontSize(10).font("Helvetica-Bold");
    doc.text("Date", 50, tableTop);
    doc.text("Merchant/Description", 130, tableTop);
    doc.text("Category", 320, tableTop);
    doc.text("Amount (KES)", 450, tableTop);

    doc
      .moveTo(50, tableTop + 15)
      .lineTo(550, tableTop + 15)
      .strokeColor("#CCCCCC")
      .stroke();
    doc.moveDown(1);

    // 7. RENDER ROWS
    let y = tableTop + 25;
    doc.font("Helvetica").fontSize(9);

    transactions.forEach((tx) => {
      // Automatic Page Break Logic
      if (y > 700) {
        doc.addPage();
        y = 50; // Reset Y on new page
      }

      const date = new Date(tx.created_at).toLocaleDateString("en-GB");
      const amountColor = tx.type === "income" ? "#2E7D32" : "#C62828";
      const displayAmount =
        tx.type === "income"
          ? `+${parseFloat(tx.amount).toLocaleString()}`
          : `-${parseFloat(tx.amount).toLocaleString()}`;

      doc.fillColor("#000").text(date, 50, y);
      doc.text(tx.merchant.substring(0, 25), 130, y);
      doc.text(tx.category || "General", 320, y);
      doc
        .fillColor(amountColor)
        .text(displayAmount, 450, y, { width: 100, align: "left" });

      y += 20;
    });

    // 8. FOOTER (Page Numbers)
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      doc
        .fontSize(8)
        .fillColor("gray")
        .text(
          `Page ${i + 1} of ${range.count} | Generated by KES Tracker`,
          50,
          750,
          { align: "center" },
        );
    }

    doc.end();
  } catch (error) {
    console.error("PDF Generation Error:", error);
    res.status(500).json({ error: "Could not generate report" });
  }
};
