const Transaction = require("../models/TransactionModel");
const User = require("../models/UserModel");
const PDFDocument = require("pdfkit");

exports.generatePDF = async (req, res) => {
  try {
    const userId = req.user;

    // 1. Fetch data from PostgreSQL
    const user = await User.findById(userId);
    const transactions = await Transaction.findAll(userId);
    const summary = await Transaction.getSummary(userId);

    if (!user) {
      return res.status(404).json({ error: "User not found" });
    }

    // 2. Initialize PDF
    const doc = new PDFDocument({ margin: 50 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=KES_Tracker_Report.pdf`,
    );
    doc.pipe(res);

    // 3. HEADER & BRANDING
    doc
      .fontSize(22)
      .fillColor("#2E7D32")
      .text("KES TRACKER", { align: "right" });
    doc
      .fontSize(10)
      .fillColor("#000")
      .text("Professional Financial Statement", { align: "right" });
    doc.moveDown();

    // 4. USER DETAILS
    doc.fontSize(12).text(`Account Holder: ${user.full_name}`);
    doc.text(`Phone Number: ${user.phone_number}`);
    doc.text(`Report Date: ${new Date().toLocaleDateString("en-GB")}`);
    doc.moveDown();
    doc.rect(50, doc.y, 500, 1).fill("#EEEEEE");
    doc.moveDown();

    // 5. SUMMARY BOX (ENHANCED)
    const boxTop = doc.y;
    doc.rect(50, boxTop, 500, 90).fillAndStroke("#f9f9f9", "#2E7D32"); // Green border box

    doc
      .fillColor("#2E7D32")
      .fontSize(14)
      .text("Account Overview", 70, boxTop + 10);

    doc.fillColor("#000").fontSize(10);
    doc.text(
      `Total Income:   KES ${summary.totalIncome.toLocaleString()}`,
      70,
      boxTop + 35,
    );
    doc.text(
      `Total Expense:  KES ${summary.totalExpense.toLocaleString()}`,
      70,
      boxTop + 50,
    );

    const balanceColor = summary.currentBalance >= 0 ? "#1B5E20" : "#C62828";
    doc
      .fontSize(12)
      .fillColor(balanceColor)
      .font("Helvetica-Bold")
      .text(
        `Net Balance:    KES ${summary.currentBalance.toLocaleString()}`,
        70,
        boxTop + 70,
      );

    doc.font("Helvetica").fillColor("#000").moveDown(4);

    // --- CATEGORY BREAKDOWN LOGIC ---
    // We calculate this on the fly from the transactions fetched
    const categories = {};
    transactions
      .filter((t) => t.type === "expense")
      .forEach((t) => {
        // Attempt to guess category from merchant name or keep it as 'Other'
        const cat = t.merchant.toLowerCase().includes("kplc")
          ? "Utilities"
          : t.merchant.toLowerCase().includes("smith")
            ? "Personal"
            : "General";
        categories[cat] = (categories[cat] || 0) + parseFloat(t.amount);
      });

    if (Object.keys(categories).length > 0) {
      doc.fontSize(12).text("Expense Breakdown", { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(9);
      Object.entries(categories).forEach(([name, amt]) => {
        doc.text(`${name}: KES ${amt.toLocaleString()}`);
      });
      doc.moveDown();
    }
    // --- END BREAKDOWN ---

    doc.rect(50, doc.y, 500, 1).fill("#EEEEEE");
    doc.moveDown();

    // 6. TRANSACTION TABLE
    doc
      .fillColor("#000")
      .fontSize(14)
      .text("Transaction History", { underline: true });
    doc.moveDown();

    const tableTop = doc.y;
    doc.fontSize(10).text("Date", 50, tableTop);
    doc.text("Description/Merchant", 150, tableTop);
    doc.text("Type", 350, tableTop);
    doc.text("Amount (KES)", 450, tableTop);
    doc.moveDown();
    doc.rect(50, doc.y, 450, 0.5).fill("#CCCCCC");
    doc.moveDown(0.5);

    transactions.forEach((tx) => {
      const date = new Date(tx.created_at).toLocaleDateString("en-GB");
      const amountColor = tx.type === "income" ? "#2E7D32" : "#C62828";

      doc
        .fillColor("#000")
        .fontSize(9)
        .text(date, 50)
        .text(tx.merchant.substring(0, 30), 150)
        .text(tx.type.toUpperCase(), 350)
        .fillColor(amountColor)
        .text(tx.amount.toLocaleString(), 450);

      doc.moveDown(0.8);
    });

    // 7. FOOTER
    doc
      .fontSize(8)
      .fillColor("gray")
      .text(
        "Generated by KES Tracker AI. This is a computer-generated document.",
        50,
        750,
        { align: "center" },
      );

    doc.end();
  } catch (error) {
    console.error("PDF Generation Error:", error);
    res.status(500).json({ error: "Could not generate report" });
  }
};
